version: 2.1.0.{build}
image: Visual Studio 2017

configuration:
  - Release
environment:
  PROJECT: toofz.NecroDancer.Leaderboards.LeaderboardsService
  PROJECT_PACKAGE: toofz-leaderboards-service-v%APPVEYOR_BUILD_VERSION%.msi
  COVERALLS_REPO_TOKEN:
    secure: a1r9kZtVxhlqjupy+BjSTg7vOxO0RVFMQzf9D1DVU9AGeroonpzehiEsSjs39kWu
artifacts:
  - path: Installer\bin\$(configuration)\$(PROJECT_PACKAGE)
    name: LeaderboardsService
cache:
  - packages -> **\packages.config
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=

before_build:
  - appveyor-retry nuget restore -DisableParallelProcessing
build:
  project: $(PROJECT).sln
  verbosity: minimal

test_script:
  - ps: |
      $project = $env:PROJECT
      $configuration = $env:CONFIGURATION

      [xml]$xml = Get-Content "$project.Tests\packages.config"
      $version = ($xml.packages.package | ? { $_.id -eq 'OpenCover' }).version

      & "packages\OpenCover.$version\tools\OpenCover.Console.exe" `
        -register:user `
        -target:'vstest.console.exe' `
        -targetargs:".\$project.Tests\bin\$configuration\$project.Tests.dll" `
        -filter:'+[LeaderboardsService*]*'
      if ($LASTEXITCODE -ne 0) { throw "Execution failed with exit code $LASTEXITCODE" }
after_test:
  - ps: |
      if (Test-Path Env:\APPVEYOR_PULL_REQUEST_NUMBER) {
        $msg = 'The environment variable "COVERALLS_REPO_TOKEN" is a secure environment variable. ' + `
               'Secure environment variables are not available during pull request builds. ' + `
               'Code coverage results were not uploaded.'
        Write-Output $msg
      } elseif (!(Test-Path Env:\COVERALLS_REPO_TOKEN)) {
        $msg = 'The environment variable "COVERALLS_REPO_TOKEN" is not set. ' + `
               'Code coverage results were not uploaded.'
        Write-Warning $msg
      } else {
        [xml]$xml = Get-Content "$env:PROJECT.Tests\packages.config"
        $version = ($xml.packages.package | ? { $_.id -eq 'coveralls.io' }).version

        & "packages\coveralls.io.$version\tools\coveralls.net.exe" `
          --opencover results.xml `
          -r $env:COVERALLS_REPO_TOKEN
        # coveralls.net does not return a non-zero exist code on error.
        if ($LASTEXITCODE -ne 0) { throw "Execution failed with exit code $LASTEXITCODE" }

        Write-Output 'Code coverage results have been uploaded.'
      }

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true
