version: $(VersionPrefix).{build}
image: Visual Studio 2017

skip_branch_with_pr: true
skip_commits:
  files:
    - LICENSE
    - README.md
configuration:
  - Release
environment:
  VersionPrefix: 0.0.0
  VersionSuffix: dev
  FileVersion: '%APPVEYOR_BUILD_VERSION%'
  PackageServerApiKey:
    secure: XZmbJDCK5oiqhbLt1y7UXM6aCYPpF2tm/bJMUJzBsCe1fd2TuwXyaz99RN+bDpHw
  PROJECT_PACKAGE: toofz-leaderboards-service-v%APPVEYOR_BUILD_VERSION%.msi
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
artifacts:
  - path: Installer\bin\$(configuration)\$(PROJECT_PACKAGE)
    name: LeaderboardsService
  
before_build:
  - nuget restore -Verbosity quiet
build:
  project: LeaderboardsService.sln
  verbosity: minimal
  
test_script:
  - ps: |
      $projectPath = Resolve-Path .\LeaderboardsService.Tests\LeaderboardsService.Tests.csproj
      msbuild $projectPath /nologo /verbosity:minimal /target:Test

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true
