coverage:
  notify:
    slack:
      default:
        url: secret:WfbB0cVb5hA1u1I9ZMX2hk0IKYSgG+eQmBSvV7oX3YduIZiaNN3RG+5bNYZf/WwWvwexMUD0PFurn9VXPFGUYWt1LyzhLhjg6DegWwng/AehoRPy2dTC5hylb0U6dfCSiA6bApcuky0GeY7R2GpLOKgSezzzdT7ydePCBCefyXM=
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null