//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.NecroDancer.Leaderboards.LeaderboardsService.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.NecroDancer.Leaderboards.LeaderboardsService.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;&lt;response&gt;&lt;appID&gt;247080&lt;/appID&gt;&lt;appFriendlyName&gt;247080&lt;/appFriendlyName&gt;&lt;leaderboardID&gt;2047387&lt;/leaderboardID&gt;&lt;totalLeaderboardEntries&gt;319&lt;/totalLeaderboardEntries&gt;&lt;entryStart&gt;1&lt;/entryStart&gt;&lt;entryEnd&gt;319&lt;/entryEnd&gt;&lt;resultCount&gt;319&lt;/resultCount&gt;&lt;entries&gt;&lt;entry&gt;&lt;steamid&gt;76561197998799529&lt;/steamid&gt;&lt;score&gt;134377&lt;/score&gt;&lt;rank&gt;1&lt;/rank&gt;&lt;ugcid&gt;849347241492683863&lt;/ugcid&gt;&lt;details&gt;&lt;![CDATA[0b00000001000000]]&gt;&lt;/details&gt;&lt;/entry&gt;&lt;entry&gt;&lt;steamid&gt;76561198093336562&lt;/ste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LeaderboardEntries_2047387_1 {
            get {
                return ResourceManager.GetString("LeaderboardEntries_2047387_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;appID&gt;247080&lt;/appID&gt;
        ///  &lt;appFriendlyName&gt;247080&lt;/appFriendlyName&gt;
        ///  &lt;leaderboardID&gt;2047540&lt;/leaderboardID&gt;
        ///  &lt;totalLeaderboardEntries&gt;8462&lt;/totalLeaderboardEntries&gt;
        ///  &lt;entryStart&gt;1&lt;/entryStart&gt;
        ///  &lt;entryEnd&gt;5001&lt;/entryEnd&gt;
        ///  &lt;nextRequestURL&gt;&lt;![CDATA[http://steamcommunity.com/stats/247080/leaderboards/2047540/?xml=1&amp;start=5002]]&gt;&lt;/nextRequestURL&gt;
        ///  &lt;resultCount&gt;5001&lt;/resultCount&gt;
        ///  &lt;entries&gt;
        ///    &lt;entry&gt;
        ///      &lt;steamid&gt;76561198287 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LeaderboardEntries_2047540_1 {
            get {
                return ResourceManager.GetString("LeaderboardEntries_2047540_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;appID&gt;247080&lt;/appID&gt;
        ///  &lt;appFriendlyName&gt;247080&lt;/appFriendlyName&gt;
        ///  &lt;leaderboardID&gt;2047540&lt;/leaderboardID&gt;
        ///  &lt;totalLeaderboardEntries&gt;8462&lt;/totalLeaderboardEntries&gt;
        ///  &lt;entryStart&gt;5002&lt;/entryStart&gt;
        ///  &lt;entryEnd&gt;8462&lt;/entryEnd&gt;
        ///  &lt;resultCount&gt;3461&lt;/resultCount&gt;
        ///  &lt;entries&gt;
        ///    &lt;entry&gt;
        ///      &lt;steamid&gt;76561198065689522&lt;/steamid&gt;
        ///      &lt;score&gt;2335&lt;/score&gt;
        ///      &lt;rank&gt;5002&lt;/rank&gt;
        ///      &lt;ugcid&gt;856099859412134689&lt;/ugcid&gt;
        ///      &lt;detai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LeaderboardEntries_2047540_2 {
            get {
                return ResourceManager.GetString("LeaderboardEntries_2047540_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;response&gt;
        ///  &lt;appID&gt;247080&lt;/appID&gt;
        ///  &lt;appFriendlyName&gt;247080&lt;/appFriendlyName&gt;
        ///  &lt;leaderboardCount&gt;2&lt;/leaderboardCount&gt;
        ///  &lt;leaderboard&gt;
        ///    &lt;url&gt;http://steamcommunity.com/stats/247080/leaderboards/2047387/?xml=1&lt;/url&gt;
        ///    &lt;lbid&gt;2047387&lt;/lbid&gt;
        ///    &lt;name&gt;DLC HARDCORE All Chars DLC_PROD&lt;/name&gt;
        ///    &lt;display_name&gt;All Characters (DLC) Score (Amplified)&lt;/display_name&gt;
        ///    &lt;entries&gt;319&lt;/entries&gt;
        ///    &lt;sortmethod&gt;2&lt;/sortmethod&gt;
        ///    &lt;displaytype&gt;1&lt;/di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Leaderboards_247080 {
            get {
                return ResourceManager.GetString("Leaderboards_247080", resourceCulture);
            }
        }
    }
}
